import { NewExpense } from "@/db/types";

export const fakeExpenseData: NewExpense[] = [
  {
    description: "맛있는 햄버거와 콜라를 처먹음",
    title: "메가 커피",
    amount: 5.0,
    userId: 1,
    categoryId: 1,
  },
  {
    description: "옷이 필요해서 새 티를 장만함",
    title: "Nike store",
    amount: 55.0,
    userId: 1,
    categoryId: 2,
  },
  {
    description: "퇴근 길에 다리가 너무 아파서 택시탐",
    title: "카카오 택시",
    amount: 30.0,
    userId: 1,
    categoryId: 3,
  },
  {
    description: "모던 리액트 Deep dive 구매",
    title: "교보 문고",
    amount: 40.0,
    userId: 1,
    categoryId: 4,
  },
  {
    description: "친구 선물로 그래픽카드를 구매함",
    title: "amazon shop",
    amount: 180.5,
    userId: 1,
    categoryId: 5,
  },
  {
    description: "친구 선물로 메모리 구매함",
    title: "temu shop",
    amount: 180.5,
    userId: 1,
    categoryId: 5,
  },
  {
    description: "친구 선물로 파워서플라이 구매함",
    title: "amazon shop",
    amount: 180.5,
    userId: 1,
    categoryId: 5,
  },
  {
    description: "netflix 구독함",
    title: "Netflix",
    amount: 10.0,
    userId: 1,
    categoryId: 6,
  },
  {
    description: "netflix 구독함",
    title: "Netflix",
    amount: 10.0,
    userId: 1,
    categoryId: 6,
  },
  {
    description: "netflix 구독함",
    title: "Netflix",
    amount: 10.0,
    userId: 1,
    categoryId: 6,
  },
  {
    description: "벽면 인테리어",
    title: "Hyphend Design",
    amount: 860.0,
    userId: 1,
    categoryId: 7,
  },
  {
    description: "벽면 인테리어",
    title: "Hyphend Design",
    amount: 860.0,
    userId: 1,
    categoryId: 7,
  },
  {
    description: "벽면 인테리어",
    title: "Hyphend Design",
    amount: 860.0,
    userId: 1,
    categoryId: 7,
  },
  {
    description: "노래방",
    title: "수 노래방",
    amount: 860.0,
    userId: 1,
    categoryId: 6,
  },
  {
    description: "벽면 인테리어",
    title: "Hyphend Design",
    amount: 860.0,
    userId: 1,
    categoryId: 7,
  },
  {
    description: "벽면 인테리어",
    title: "Hyphend Design",
    amount: 860.0,
    userId: 1,
    categoryId: 7,
  },
  {
    description: "노래방",
    title: "수 노래방",
    amount: 860.0,
    userId: 1,
    categoryId: 6,
  },
  {
    description: "노래방",
    title: "수 노래방",
    amount: 860.0,
    userId: 1,
    categoryId: 6,
  },
  {
    description: "맛있는 햄버거와 콜라를 처먹음",
    title: "메가 커피",
    amount: 5.0,
    userId: 1,
    categoryId: 1,
  },
  {
    description: "맛있는 햄버거와 콜라를 처먹음",
    title: "메가 커피",
    amount: 5.0,
    userId: 1,
    categoryId: 1,
  },
  {
    description: "모던 리액트 Deep dive 구매",
    title: "교보 문고",
    amount: 40.0,
    userId: 1,
    categoryId: 4,
  },
  {
    description: "퇴근 길에 다리가 너무 아파서 택시탐",
    title: "카카오 택시",
    amount: 30.0,
    userId: 1,
    categoryId: 3,
  },
  {
    description: "퇴근 길에 다리가 너무 아파서 택시탐",
    title: "카카오 택시",
    amount: 30.0,
    userId: 1,
    categoryId: 3,
  },
];
